- name: Kubectl playbook
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  - name: update APT Package Manager
    apt:
      update_cache: yes

  - name: install dependency packages
    apt:
      name={{ item }}
    with_items:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - curl
      - software-properties-common

  - name: Get apt Key
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

  - name: Echo
    shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

  - name: update APT Package Manager
    apt:
      update_cache: yes

  - name: Start minikube
    shell: | 
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube  
      sudo mv minikube /usr/local/bin/
    register: command_output

  - name: create playbook
    copy:
      dest: ./minikube.yml
      content: |
        - name: Deploy playbook
          hosts: localhost
          user: ubuntu
          become: false
          tasks:

          - name: get image
            shell: |
              minikube start
              kubectl create deployment jdock --image=stuart1389/jsdock:v1
              kubectl expose deployment/jdock --type="NodePort" --port 8080 --name node-service
              kubectl scale deployments/jdock --replicas=12
            register: command_output

  - name: 10. Change File permissions so that it can be executed
    file:
      path: ./minikube.yml
      owner: ubuntu
      group: ubuntu
      mode: '777'

  - name: 11. Execute playbook
    become: no
    shell: ansible-playbook minikube.yml
