- name: Kubectl playbook
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  - name: update APT Package Manager
    apt:
      update_cache: yes

  - name: install dependency packages
    apt:
      name={{ item }}
    with_items:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - curl
      - software-properties-common

  - name: Get apt Key
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

  - name: update APT Package Manager
    apt:
      update_cache: yes

  - name: Getting minikube ready
    shell: | 
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube  
      sudo mv minikube /usr/local/bin/
    register: command_output

  - name: Deploy image with kubernetes
    become: no
    shell: |
      minikube start
      kubectl create deployment jsdock --image=stuart1389/jsdock:64
      kubectl expose deployment/jsdock --type="NodePort" --port 8090 --name jsdock-service
      kubectl scale deployments/jsdock --replicas=12
    register: command_output
